addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"     % "2.1.5")
addSbtPlugin("pl.project13.scala"  % "sbt-jmh"          % "0.4.7")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"     % "0.14.3")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"     % "2.5.5")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"     % "0.5.2")
